---
# tasks file for base-database
- name: Check if ufw/firewall is enabled
  shell: ufw status
  changed_when: False
  ignore_errors: True
  register: ufw_check
- debug:
    msg: "{{ ufw_check }}"

- name: Expose default port for postgresql client usage
  firewalld:
    port: 5432/TCP
    permanent: yes
    state: enabled
  ignore_errors: yes

- name: Install latest postgresql
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - postgresql
      - postgresql-contrib

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Enable PostgreSQL
  service:
    name: postgresql
    enabled: yes
