---
# tasks file for base-database
- name: Check if ufw/firewall is enabled
  shell: ufw status
  changed_when: False
  ignore_errors: True
  register: ufw_check
- debug:
    msg: "{{ ufw_check }}"

- name: Enable UFW firewall
  ufw:
    state: enabled
  become: true

- name: Set logging to ON
  ufw:
    logging: on
  become: true

- name: Allow access to ssh connection for all
  ufw:
    rule: allow
    port: ssh
    proto: tcp
  become: yes

- name: Allow access to port 5432 from the IP application host (192.168.56.20)
  ufw:
    rule: allow
    port: 5432
    proto: tcp
    src: "{{ item }}"
    log: yes
  loop:
    - 192.168.56.20
  become: true

- name: Install latest postgresql
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - postgresql
      - postgresql-contrib
  become: true

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  become: true

- name: Enable PostgreSQL
  service:
    name: postgresql
    enabled: yes
  become: true
