---
# tasks file for base-nginx
- name: Check if ufw/firewall is enabled
  shell: ufw status
  changed_when: False
  ignore_errors: True
  register: ufw_check
- debug:
    msg: "{{ ufw_check }}"

- name: Enable HTTP protocol for web application communication
  firewalld:
    port: 80/HTTP
    permanent: yes
    state: enabled
  ignore_errors: yes

- name: Install nginx web/proxy server
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
