---
# tasks file for base-nginx
- name: Check if ufw/firewall is enabled
  shell: ufw status
  changed_when: False
  ignore_errors: yes
  register: ufw_check
- debug:
    msg: "{{ ufw_check }}"

- name: Enable UFW firewall
  ufw:
    state: enabled
  become: yes

- name: Set logging to ON
  ufw:
    logging: on
  become: yes

- name: Allow access to port 80 for all incoming request
  ufw:
    rule: allow
    port: 80
    proto: tcp
  become: yes

- name: Install nginx web/proxy server
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - nginx
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
  become: yes
