---
# handlers file for base-nginx
- name: Start Nginx
  service: name=nginx state=started

- name: Restart Nginx
  service: name=nginx state=restarted

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
