---
# tasks file for database-user
- name: package dependency installation (dependence)
  apt:
    name: "{{ dependencies }}"
    update_cache: yes
    state: present
  vars:
    dependencies:
      - libpq-dev
      - python3-pip
      - acl

- name: psycopg2 python package installation (dependence)
  pip:
    name: psycopg2

- name: Create a database for the application
  postgresql_db:
    name: "{{ db_name }}"
    template: template0
    encoding: UTF8
  become_user: postgres

- name: Grant permission for a user on the created database
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_user_pass }}"
    priv: ALL
    expires: infinity
  become_user: postgres
